INSERT INTO artists (name, genre) VALUES ("D'Angelo", "Neo-Soul");
INSERT INTO artists (name, genre) VALUES ("Horse Feathers", "Folk");
INSERT INTO artists (name, genre) VALUES ("Lauryn Hill", "Hip Hop");
INSERT INTO artists (name, genre) VALUES ("M.I.A.", "Hip Hop");
INSERT INTO artists (name, genre) VALUES ("Radiohead", "Electronic Rock");
INSERT INTO artists (name, genre) VALUES ("Santigold", "Alternative Hip Hop");
INSERT INTO artists (name, genre) VALUES ("TV On The Radio", "Rock");

INSERT INTO albums (artist_id, title, year) VALUES (1, "Brown Sugar", 1995);
INSERT INTO albums (artist_id, title, year) VALUES (1, "Voodoo", 2000);
INSERT INTO albums (artist_id, title, year) VALUES (2, "House with No Home", 2008);
INSERT INTO albums (artist_id, title, year) VALUES (3, "The Miseducation of Lauryn Hill", 1998);
INSERT INTO albums (artist_id, title, year) VALUES (4, "Kala", 2007);
INSERT INTO albums (artist_id, title, year) VALUES (5, "In Rainbows", 2007);
INSERT INTO albums (artist_id, title, year) VALUES (5, "Amnesiac", 2001);
INSERT INTO albums (artist_id, title, year) VALUES (6, "Santigold", 2008);
INSERT INTO albums (artist_id, title, year) VALUES (7, "Dear Science", 2008);
INSERT INTO albums (artist_id, title, year) VALUES (7, "Desperate Youth, Blood Thirsty Babes", 2004);

INSERT INTO songs (title, album_id, length, track_no) VALUES ("Playa Playa", 1, 426, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Devil's Pie", 1, 321, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Left & Right (Featuring Method Man And Redman)", 1, 286, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("The Line", 1, 316, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Send It On", 1, 356, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Chicken Grease", 1, 278, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("One Mo'gin", 1, 373, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("The Root", 1, 393, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Spanish Joint", 1, 344, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Feel Like Makin' Love", 1, 382, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Greatdayndamorn'/Booty", 1, 455, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Untitled (How Does It Feel)", 1, 430, 12);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Brown Sugar", 2, 263, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Alright", 2, 313, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Jonz In My Bonz", 2, 356, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Me And Those Dreamin' Eyes Of Mine", 2, 286, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Shit, Damn, Motherfucker", 2, 314, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Smooth", 2, 259, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Cruisin'", 2, 384, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("When We Get By", 2, 344, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Lady", 2, 346, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Higher", 2, 327, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Curs in the Weeds", 3, 210, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Rude to Rile", 3, 209, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Working Poor", 3, 196, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Albina", 3, 137, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("A Burden", 3, 211, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Helen", 3, 260, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Father (Reprise)", 3, 121, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Heathen's Kiss", 3, 280, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Different Gray", 3, 176, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("This Is What", 3, 189, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Father", 3, 210, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Intro", 4, 47, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Lost Ones", 4, 333, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Ex Factor", 4, 326, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("To Zion", 4, 369, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Doo Wop (That Thing)", 4, 320, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Superstar", 4, 297, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Final Hour", 4, 256, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("When It Hurts So Bad", 4, 342, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("I Used To Love Him", 4, 339, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Forgive Them Father", 4, 315, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Every Ghetto Every City", 4, 314, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Nothing Even Matters", 4, 350, 12);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Everything Is Everything", 4, 293, 13);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Miseducation Of Lauryn Hill", 4, 257, 14);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Can't Take My Eyes Off Of You", 4, 221, 15);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Tell Him", 4, 280, 16);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Bamboo Banger", 5, 298, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Bird Flu", 5, 204, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Boyz", 5, 207, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Jimmy", 5, 209, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Hussel (feat. Afrikan Boy)", 5, 265, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Mango Pickle Down River (with The Wilcannia Mob)", 5, 233, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("$20", 5, 274, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Down River", 5, 233, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("The Turn", 5, 232, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("XR2", 5, 260, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Paper Planes", 5, 204, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Come Around (feat. Timbaland)", 5, 233, 12);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("15 Step", 6, 237, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Bodysnatchers", 6, 242, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Nude", 6, 255, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Weird Fishes/Arpeggi", 6, 318, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("All I Need", 6, 228, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Faust Arp", 6, 129, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Reckoner", 6, 290, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("House Of Cards", 6, 328, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Jigsaw Falling Into Place", 6, 248, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Videotape", 6, 279, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Packt Like Sardines In A Crushd Tin Box", 7, 240, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Pyramid Song", 7, 288, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Pulk/Pull Revolving Doors", 7, 247, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("You And Whose Army?", 7, 190, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("I Might Be Wrong", 7, 293, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Knives Out", 7, 254, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Morning Bell/Amnesiac", 7, 194, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Dollars & Cents", 7, 291, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Hunting Bears", 7, 121, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Like Spinning Plates", 7, 237, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Life In A Glass House", 7, 274, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Anne", 8, 208, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Creator", 8, 213, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("I'm a Lady", 8, 223, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("LES artistes", 8, 204, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Lights Out", 8, 192, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("My Superman", 8, 180, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Say Aha", 8, 215, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("shove It", 8, 226, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Startruck", 8, 234, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Unstppable", 8, 212, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("You´ll Find A Way", 8, 180, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("You´ll Find A way(remix)", 8, 192, 12);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Halfway Home", 9, 331, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Crying", 9, 250, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Dancing Choose", 9, 176, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Stork And Owl", 9, 241, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Golden Age", 9, 251, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Family Tree", 9, 333, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Red Dress", 9, 265, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Love Dog", 9, 336, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Shout Me Out", 9, 255, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("DLZ", 9, 228, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Lover's Day", 9, 355, 11);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("The Wrong Way", 10, 278, 1);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Staring at the Sun", 10, 206, 2);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Dreams", 10, 309, 3);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("King Eternal", 10, 267, 4);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Ambulance", 10, 294, 5);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Poppy", 10, 367, 6);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Don't Love You", 10, 331, 7);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Bomb Yourself", 10, 331, 8);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Wear You Out", 10, 440, 9);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("You Could Be Love", 10, 436, 10);
INSERT INTO songs (title, album_id, length, track_no) VALUES ("Staring at the Sun (Demo)", 10, 377, 11);

INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Dance Jams", 38, 4, 3);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Dance Jams", 53, 5, 4);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Dance Jams", 60, 5, 4);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Dance Jams", 86, 8, 6);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Dance Jams", 9, 1, 1);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Romantic Nitez", 48, 4, 3);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Romantic Nitez", 10, 1, 1);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Romantic Nitez", 105, 9, 7);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Romantic Nitez", 88, 8, 6);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Spacey", 65, 6, 5);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Spacey", 82, 7, 5);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Spacey", 107, 10, 7);
INSERT INTO playlists (title, song_id, album_id, artist_id) VALUES ("Spacey", 99, 9, 7);
